---
layout: post
title: RAIM Directives on Security
category: statements
tags: [Security]
description: The Following are 4 simple directives intended to improve our security practice, they have been derived from the official RAIM Security Document and are intended to provide a helpful primer. Though, for more information, it is still recommended you read the full document on security.
---

## Directives on Security

The Following are 4 simple directives intended to improve our security practice, they have been derived from the official [RAIM Security Document](/uploads/raim/RAIM-Security-Document-US-Letter.pdf) and are intended to provide a helpful primer. Though, for more information, it is still recommended you read the full document on security.

## Do not ask/answer pig questions!

Pig questions can generally be defined as questions (or accusations that demand responses) that relate to your personal information or generally need-to-know information involving the revolutionary movement. Some may seem harmless enough, however it is important never to answer pig questions. Questions or accusations involving personal information, your group’s membership, your background in revolutionary work, or other non-essential and ultimately dangerous topics are to be avoided. These questions do not necessarily imply someone works with the pigs—in fact they can be asked entirely innocently. However, avoiding these questions and explaining that you are not comfortable answering them is the best course of action. As for accusations relating to the organization, such as those of involvement in illegal activity or speculations as to the demographic makeup of our members: these should never be dignified with a response. To respond to such claims only adds fuel to the flame, and regardless of the circumstance—however innocent they may be—it can serve to circulate information that is only useful to the pigs.

## Defend your anonymity!

Make sure to keep your identity as anonymous as possible without hindering your political work. The last thing we want is for the state or political opponents to be able to track us down with few hangups. Online this is difficult, however there are several tricks available for doing this, such as never using your real name on your social media accounts, and keeping real images of yourself off the net with relevance to your political work. Absolute anonymity is generally unachievable, but when it comes to reactionaries trying to gain intel on ourselves and our comrades, we must strive to enforce any roadblock we can. If a great enough challenge is presented to those trying to gather information, they may not have the resources or time to continue and may be forced to abandon it and look for other methods. Outside the net, we want to make sure that we wear masks and continue to use our pseudonyms (perhaps different than our online persona) when dealing with political work. We don’t want what we do on the web to be connected to us on the ground and vice-versa, and separating these things can only help us in our general dealings.

## Avoid illegal provocations!

Between agents of the state (whether traitor informants or undercover pigs) and the ignorant and ultimately dangerous adventurist elements of the left, there are plenty of people who could approach you with propositions of getting involved in “real resistance” to the state, in often half-baked plans for terroristic reprisal or politically confused violence. We should not engage, under any circumstance, in adventurist acts that threaten the lives of our comrades and oppressed people at this juncture. The likelihood that those who attempt to goad us into these actions are pigs is quite high, seeing as they readily use such techniques already on marginalised youth in amerika. The FBI routinely engages in entrapment and crafts (occasionally thorough) plans for adventurist attacks on the state, even supplying materials at times. We have seen this very recently with the New Black Panther Party and the uprisings following the shooting of Michael Brown, and as well the various FBI sting operations tricking Muslim youth into agreeing to carry out attacks on the united $tates government. Even if the people trying to pull us in with promises of martyrdom and “real action” are not pigs, they certainly do not assist the revolution. In fact, in their desire to go outside the realm of real organized resistance for a few exciting moments of roleplay “revolution,” they serve nothing but their own individualistic narcissism. Militant actions should only be approached on a systematic basis by an organization capable of doing whatever is deemed necessary. Adventurism ultimately works against the goals of the revolutionary organization, not with it, and needlessly threatens the lives of comrades for individual fantasies of martyrdom.

## Avoid falling for honey-traps!

Honey-traps are a method often used by the state and local law enforcement to implant spies among revolutionaries. These individual spies may undertake any number of hollow acts in order to convince people they are part of the revolutionary movement, perhaps claiming association with a particular organization or former organization to create some kind of “credentials.” Whether it be distributing materials from a particular organization, or attending a few rallies or volunteering with local activist circles, we cannot assume everyone to be entirely trustworthy simply by virtue of having the right aesthetic. Agents will try to use these same tactics to embed themselves in and spy on our movement. There are two ways we can resist damage from these traps: (1) through the principles laid out in all the aforementioned directives and (2) through creating a political culture that emphasizes ideological rigor and dedicated political work. This political culture should replace the liberal and postmodernist tendencies to emphasize social background or lifestyle over the content of someone’s political work and dedication. This is doubly true for those who boast an incredible set of credentials without providing much to the project at hand, as many agents will boast having been involved with the staple communist organizations, even ostensible former Black Panthers and such. All trust should be earned, and no one should be assumed to be revolutionary simply because they appear as such. This should not encourage undue suspicion, but encourage the creation of politically secure environments in which agents have an incredibly difficult time integrating. We cannot stop all attempted infiltrators, however with dedication and careful practice, we can hope to stop a vast majority of them, or make their presence in and around our movements effectively useless.
